version: 3
project:
  locator: SolaceLabs_solace-client-proxy-kafka-producer
  id: SolaceLabs_solace-client-proxy-kafka-producer
  name: solace-client-proxy-kafka-producer
  teams: []
  labels:
    - java
vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    exclude:
      - "./.git"
      - "./.github"
paths:
  exclude:
    - ./.git
    - ./.github
telemetry:
  scope: full
