/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
//    `maven-publish`
    eclipse
    application
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    maven {
        url = uri("https://packages.confluent.io/maven")
    }
}

dependencies {
    implementation("org.apache.kafka:kafka-clients:2.8.2+")
    //implementation("org.apache.kafka:kafka-clients:3.3.1")
    implementation("com.solace:solace-messaging-client:1.+")
    implementation("org.slf4j:slf4j-api:1.7.36")
    implementation("org.slf4j:slf4j-simple:1.7.36")

    testImplementation("io.confluent:kafka-json-serializer:7.3.0")
}

group = "org.apache.kafka.solace"
version = "1.0-SNAPSHOT"
description = "kafkaproxy"
java.sourceCompatibility = JavaVersion.VERSION_1_8

//publishing {
//    publications.create<MavenPublication>("maven") {
//        from(components["java"])
//    }
//}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

application {
    mainClass.set("org.apache.kafka.solace.kafkaproxy.ProxyMain")
}
